log_level: debug

home_assistant:
  host: hass.home.fossar.net
  tls_enabled: true
  health_check_entities:
    - light.escalier_switch
    - light.poutre_dimmer
  subscribe_events:
    - state_changed
    - roku_command
  home_zone_name: home # Get latitude and longitude from configured zone

# This uses github.com/robfig/cron
crons:
  - expr: 0 1 * * *
    action: turn_off
    entities:
      - input_boolean.override_estrade_dehum
      - input_boolean.override_heater_bedroom
      - input_boolean.override_heater_blue
      - input_boolean.override_heater_pink
      - input_boolean.override_heater_hall
      - input_boolean.override_heater_kitchen
      - input_boolean.override_heater_living

modules:
  - internetChecker:
      name: internet
      disabled: true
      interval: 300s
      ping_host: 8.8.8.8
      max_reboot_every: 180s
      restart_entity: switch.living_fbx
  - heaterChecker:
      name: living
      interval: 5s
      schedules_file: heaters/living.yaml
  - heaterChecker:
      name: kitchen
      interval: 5s
      schedules_file: heaters/kitchen.yaml
  - heaterChecker:
      name: hall
      interval: 5s
      schedules_file: heaters/hall.yaml
  - heaterChecker:
      name: blue
      interval: 5s
      schedules_file: heaters/blue.yaml
  - heaterChecker:
      name: pink
      interval: 5s
      schedules_file: heaters/pink.yaml
  - heaterChecker:
      name: bedroom
      interval: 5s
      schedules_file: heaters/bedroom.yaml
  - freshnessChecker:
      name: zigbee_temp_sensors
      interval: 12h
      freshness: 6h
      sender: telegram
      entities:
        - sensor.dehumidifier_water_sensor_last_seen
        - sensor.kitchen_fridge_up_hum_temp_last_seen
        - sensor.outside_hum_temp_last_seen
        - sensor.z03mmc_basement_bedroom_hum_temp_last_seen
        - sensor.z03mmc_basement_cave_hum_temp_last_seen
        - sensor.z03mmc_bedroom_hum_temp_last_seen
        - sensor.z03mmc_blue_hum_temp_last_seen
        - sensor.z03mmc_hall_hum_temp_last_seen
        - sensor.z03mmc_kitchen_fridge_down_hum_temp_last_seen
        - sensor.z03mmc_kitchen_hum_temp_last_seen
        - sensor.z03mmc_living_hum_temp_last_seen
        - sensor.z03mmc_networkbox_hum_temp_last_seen
        - sensor.z03mmc_pink_hum_temp_last_seen
      template: |
        Les sensors Zigbee suivants n'ont pas donné de nouvelles depuis plus de {{ .Checker.Freshness }}:
        {{ JoinEntities .Entities "\n" "_last_seen" }}
  - freshnessChecker:
      name: zigbee_dehum_water_sensor
      interval: 60m
      freshness: 240m
      sender: telegram
      entities:
        - sensor.dehumidifier_water_sensor_last_seen
      template: |
        Pas de nouvelle depuis plus de {{ .Checker.Freshness }} du water sensor pour le déshumidificateur !
  - temperatureChecker:
      interval: 300s
      sender: telegram
      sensors:
        - entity: sensor.kitchen_fridge_up_hum_temp_temperature
          temp_threshold: 11
        - entity: sensor.outside_hum_temp_temperature
          temp_threshold: 38
        - entity: sensor.z03mmc_basement_bedroom_hum_temp_temperature
          temp_threshold: 24
        - entity: sensor.z03mmc_basement_cave_hum_temp_temperature
          temp_threshold: 24
        - entity: sensor.z03mmc_basement_main_hum_temp_temperature
          temp_threshold: 24
        - entity: sensor.z03mmc_bedroom_hum_temp_temperature
          temp_threshold: 24
        - entity: sensor.z03mmc_blue_hum_temp_temperature
          temp_threshold: 24
        - entity: sensor.z03mmc_hall_hum_temp_temperature
          temp_threshold: 23
        - entity: sensor.z03mmc_kitchen_fridge_down_hum_temp_temperature
          temp_threshold: 9
        - entity: sensor.z03mmc_kitchen_hum_temp_temperature
          temp_threshold: 23
        - entity: sensor.z03mmc_living_hum_temp_temperature
          temp_threshold: 23
        - entity: sensor.z03mmc_networkbox_hum_temp_temperature
          temp_threshold: 36
        - entity: sensor.z03mmc_pink_hum_temp_temperature
          temp_threshold: 24
      date_begin: 15/10
      date_end: 01/05
      send_message_interval: 12h
      template: |
        Les sensors suivants ont une température excédant la limite:
        {{ JoinEntities .Entities "\n" "_hum_temp_temperature"}}

triggers:
  - alert:
      trigger_entities:
        - binary_sensor.dehumidifier_water_sensor_water_leak
      sender: statusled
  - alert:
      trigger_entities:
        - binary_sensor.dehumidifier_water_sensor_water_leak
      sender: telegram
      templates:
        binary_sensor.dehumidifier_water_sensor_water_leak:
          msg_template: |-
            {{- if not (eq (GetOldStateAttrAsBool .Event "water_leak") (GetNewStateAttrAsBool .Event "water_leak")) }}
              {{- if GetNewStateAttrAsBool .Event "water_leak" }}
              ⚠ Le déshumidificateur est plein !
              {{- else }}
              Le déshumidificateur a été vidé 👍 !
              {{- end }}
            {{- end }}
  - randomLights:
      name: randomLights
      trigger_entities:
        - input_boolean.random_lights
      nb_slots: 3
      time_end: 00:45:00
      odds: 5
      refresh_every: 1m
      lights:
        - entity: light.poutre_dimmer
          min_duration: 30m
          max_duration: 2h
        - entity: light.escalier_switch
          min_duration: 15m
          max_duration: 2h
        - entity: light.dressing_switch
          min_duration: 15m
          max_duration: 1h
        - entity: light.piano_switch
          min_duration: 15m
          max_duration: 1h
        - entity: light.living_ball_switch
          min_duration: 30m
          max_duration: 2h
  - heaterCheckersDisabler: # Globally disable heaters' programmation
      name: heater_prog_disabler
      temp: 17
      trigger_entities:
        - input_boolean.override_heater_prog
      #checkers:
      #  - blue
  - calendarLights:
      name: calendarLights
      disabled: false
      trigger_entities:
        - calendar.light_.*
  - dehumidifier:
      name: dehum_bedroom
      disabled: false
      trigger_entities:
        - sensor.estrade_am2301_humidity
        - input_boolean.override_estrade_dehum
      switch_entity: switch.estrade_relay
      time_beg: 10:00:00
      time_end: 21:30:00
      threshold_min: 53
      threshold_max: 60
      manual_override: input_boolean.override_estrade_dehum
  - harmony:
      name: harmony
      disabled: false
      trigger_events:
        - roku_command
      work_actions:
        - key: Left
          only_dark: true
          commands:
            # TV end
            - {entity: light.poutre_dimmer, service: turn_on, brightness: 128}
            - {entity: light.living_ball_switch, service: turn_off}
            - {entity: light.escalier_switch, service: turn_on}
            - {delay: 250ms}
            - {entity: light.table_dimmer, service: turn_off}
        - key: Right
          only_dark: true
          commands:
            # Gaming
            - {entity: light.poutre_dimmer, service: turn_off}
            - {entity: light.living_ball_switch, service: turn_off}
            - {entity: light.escalier_switch, service: turn_on}
            - {delay: 250ms}
            - {entity: light.table_dimmer, service: turn_off}
            - {delay: 250ms}
            - {entity: light.piano_switch, service: turn_off}
            - {delay: 250ms}
            - {entity: light.dressing_switch, service: turn_off}
            - {delay: 250ms}
            - {entity: light.entree_switch, service: turn_off}
        - key: Select
          only_dark: true
          commands:
            # Movies
            - {entity: light.poutre_dimmer, service: turn_on, brightness: 25}
            - {entity: light.living_ball_switch, service: turn_on}
            - {entity: light.escalier_switch, service: turn_off}
            - {delay: 250ms}
            - {entity: light.table_dimmer, service: turn_off}
            - {delay: 250ms}
            - {entity: light.piano_switch, service: turn_off}
            - {delay: 250ms}
            - {entity: light.dressing_switch, service: turn_off}
            - {delay: 250ms}
            - {entity: light.entree_switch, service: turn_off}
        - key: Up
          commands:
            - {entity: light.escalier_switch, service: toggle}
        - key: Down
          commands:
            - {entity: light.poutre_dimmer, service: toggle}
        - key: Back
          commands:
            - {entity: light.living_ball_switch, service: toggle}
        - key: Play
          commands:
            - {entity: light.escalier_switch, service: toggle}
        - key: Rev
          commands:
            - {entity: light.poutre_dimmer, service: turn_on, brightness: 127}
        - key: Fwd
          commands:
            - {entity: light.poutre_dimmer, service: turn_off}
        - key: Search
          commands:
            - {entity: light.poutre_dimmer, service: turn_on, brightness: 25}
        - key: Info
          commands:
            - {entity: light.poutre_dimmer, service: turn_on, brightness: 255}
        - key: Home
          commands:
            - {entity: light.table_dimmer, service: turn_on, brightness: 255}
        - key: InstantReplay
          commands:
            - {entity: light.table_dimmer, service: turn_off}
